### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SpringlesMcOutrage** [yuta-belmont/metamask_bf#5]
Warning (from warnings module):
  File "C:\Users\romka\OneDrive\Робочий стіл\1.py", line 11
    driver = webdriver.Chrome(chrome_options=opt)
DeprecationWarning: use options instead of chrome_options
Traceback (most recent call last):
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    creationflags=self.creationflags)
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\romka\OneDrive\Робочий стіл\1.py", line 11, in <module>
    driver = webdriver.Chrome(chrome_options=opt)
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\romka\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

what i must to do?

**Comment by fobabs** [comment]
For Linux: Try `sudo apt-get install chromium-chromedriver`

**Comment by toolscrackedx** [comment]
driver = webdriver.Chrome(chrome_options=opt)
change to 
chrome_driver_path = 'C:\\chromedriver\\chromedriver.exe'
driver = webdriver.Chrome(executable_path=chrome_driver_path)

you can find chromedriver
here
https://chromedriver.chromium.org/
