### ISSUE TITLE
I have a problem with my PC, can you help me? I am using metamask_bf_v2.py

### ISSUE THREAD

**Issue by nsiqwe** [yuta-belmont/metamask_bf#7]
DevTools listening on ws://127.0.0.1:51259/devtools/browser/9b92077b-9960-4c46-80c9-d8eab423bfdd
START: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] ['xxx', 'xxxx', 'xxxx', 'xxxx', 'xxxx', 'xxxx', 'xxx', 'xxxx', 'xxxx', 'xxxx', 'xx', 'xxxx']
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\metamask_bf_v2\metamask_bf_v2\metamask_bf_v2.py", line 64, in <module>
    driver.find_element(by = By.CSS_SELECTOR, value = '#app-content > div > div.main-container-wrapper > div > div > div > form > div.import-srp__container > div.actionable-message.actionable-message--danger.import-srp__srp-error.actionable-message--with-icon') #check to see if invalid message pops up
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#app-content > div > div.main-container-wrapper > div > div > div > form > div.import-srp__container > div.actionable-message.actionable-message--danger.import-srp__srp-error.actionable-message--with-icon"}
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x0054DF13+2219795]
        Ordinal0 [0x004E2841+1779777]
        Ordinal0 [0x003F423D+803389]
        Ordinal0 [0x00423025+995365]
        Ordinal0 [0x004231EB+995819]
        Ordinal0 [0x00450F52+1183570]
        Ordinal0 [0x0043E844+1108036]
        Ordinal0 [0x0044F192+1175954]
        Ordinal0 [0x0043E616+1107478]
        Ordinal0 [0x00417F89+950153]
        Ordinal0 [0x00418F56+954198]
        GetHandleVerifier [0x00842CB2+3040210]
        GetHandleVerifier [0x00832BB4+2974420]
        GetHandleVerifier [0x005E6A0A+565546]
        GetHandleVerifier [0x005E5680+560544]
        Ordinal0 [0x004E9A5C+1808988]
        Ordinal0 [0x004EE3A8+1827752]
        Ordinal0 [0x004EE495+1827989]
        Ordinal0 [0x004F80A4+1867940]
        BaseThreadInitThunk [0x771EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77D47A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77D47A4E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\metamask_bf_v2\metamask_bf_v2\metamask_bf_v2.py", line 97, in <module>
    elem = driver.find_element(by = By.XPATH, value = '/html/body/div[1]/div/div[3]/div/div/div/div[2]/div/div[1]/div/div/div/div[2]/span[1]') #find balance element
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div[3]/div/div/div/div[2]/div/div[1]/div/div/div/div[2]/span[1]"}
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x0054DF13+2219795]
        Ordinal0 [0x004E2841+1779777]
        Ordinal0 [0x003F423D+803389]
        Ordinal0 [0x00423025+995365]
        Ordinal0 [0x004231EB+995819]
        Ordinal0 [0x00450F52+1183570]
        Ordinal0 [0x0043E844+1108036]
        Ordinal0 [0x0044F192+1175954]
        Ordinal0 [0x0043E616+1107478]
        Ordinal0 [0x00417F89+950153]
        Ordinal0 [0x00418F56+954198]
        GetHandleVerifier [0x00842CB2+3040210]
        GetHandleVerifier [0x00832BB4+2974420]
        GetHandleVerifier [0x005E6A0A+565546]
        GetHandleVerifier [0x005E5680+560544]
        Ordinal0 [0x004E9A5C+1808988]
        Ordinal0 [0x004EE3A8+1827752]
        Ordinal0 [0x004EE495+1827989]
        Ordinal0 [0x004F80A4+1867940]
        BaseThreadInitThunk [0x771EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77D47A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77D47A4E+238]

Press any key to continue . . . [9064:1716:0907/200053.954:ERROR:device_event_log_impl.cc(214)] [20:00:53.955] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

**Comment by toolscrackedx** [comment]
same
